#!/bin/bash

# Omacy - Ghostty Terminal Installation
# Modern terminal emulator with optimal configuration

# Load common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

# Configure Ghostty terminal
configure_ghostty() {
    print_info "Configuring Ghostty terminal..."
    
    local config_dir="$HOME/.config/ghostty"
    local config_file="$config_dir/config"
    
    # Create config directory
    mkdir -p "$config_dir"
    
    # Backup existing config if it exists
    if [ -f "$config_file" ]; then
        cp "$config_file" "$config_file.backup.$(date +%Y%m%d_%H%M%S)"
        print_info "Existing Ghostty config backed up"
    fi
    
    # Create Ghostty configuration
    cat > "$config_file" << 'EOF'
# Ghostty Terminal Configuration
# Generated by Omacy

# Font configuration
font-family = "JetBrains Mono Nerd Font"
font-size = 14

# Theme (will be updated by theme system)
theme = "catppuccin-macchiato"

# Window configuration
window-decoration = true
window-theme = "dark"
window-padding-x = 10
window-padding-y = 10

# Cursor
cursor-style = "block"
cursor-style-blink = false

# Shell integration
shell-integration = "detect"

# Performance
copy-on-select = true
confirm-close-surface = false

# Key bindings
keybind = cmd+t=new_tab
keybind = cmd+w=close_surface
keybind = cmd+n=new_window
keybind = cmd+shift+t=restore_tab
keybind = cmd+plus=increase_font_size
keybind = cmd+minus=decrease_font_size
keybind = cmd+0=reset_font_size
EOF
    
    print_status "Ghostty configuration created at $config_file"
    print_info "Features configured:"
    print_info "  JetBrains Mono Nerd Font with Catppuccin theme"
    print_info "  Optimized key bindings and shell integration"
    print_info "  Performance optimizations enabled"
}

# Main installation
main() {
    run_individual_script "ghostty.sh" "Ghostty (Modern Terminal)"
    
    # Install Ghostty via Homebrew
    if ! install_brew_package "ghostty" true "Modern terminal emulator"; then
        script_failure "ghostty" "Failed to install via Homebrew"
    fi
    
    # Configure Ghostty
    configure_ghostty
    
    script_success "ghostty"
}

# Only run main if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi