#!/bin/bash

# Omacy - Ghostty Terminal Configuration
# Configures Ghostty terminal with optimal settings

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_status() {
    echo -e "${GREEN}✅${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠️${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ️${NC} $1"
}

# Configure Ghostty terminal
configure_ghostty() {
    print_info "Configuring Ghostty terminal..."
    
    local config_dir="$HOME/.config/ghostty"
    local config_file="$config_dir/config"
    
    # Create config directory
    mkdir -p "$config_dir"
    
    # Check if config already exists
    if [ -f "$config_file" ]; then
        print_status "Ghostty config already exists"
        return 0
    fi
    
    # Create Ghostty configuration
    cat > "$config_file" << 'EOF'
# Ghostty Terminal Configuration
# Generated by Omacy

# Font configuration
font-family = "JetBrains Mono"
font-size = 14

# Theme
theme = "catppuccin-macchiato"

# Window configuration
window-decoration = true
window-theme = "dark"
window-padding-x = 10
window-padding-y = 10

# Cursor
cursor-style = "block"
cursor-style-blink = false

# Shell integration
shell-integration = "zsh"

# Performance
copy-on-select = true
confirm-close-surface = false

# Key bindings
keybind = cmd+t=new_tab
keybind = cmd+w=close_surface
keybind = cmd+n=new_window
keybind = cmd+shift+t=restore_tab
EOF
    
    print_status "Ghostty configuration created"
}

# Main execution
main() {
    configure_ghostty
    print_status "Ghostty configuration complete!"
}

# Only run main if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi